---
kind: pipeline
type: docker
name: publish

steps:
- name: publish-service-sources
  image: alpine
  environment:
    SSH_KEY:
      from_secret: github_bot_ssh_key
    ACCESS_TOKEN:
      from_secret: github_bot_access_token
  commands:
    - apk update && apk add curl bash
    - curl -s https://$${ACCESS_TOKEN}@raw.githubusercontent.com/enowars/Enowars4DevOps/master/drone-opennebula/push-services.sh | bash -s poolcide

- name: trigger-vm-image-creation
  image: plugins/downstream
  settings:
    server: https://droneci.sect.tu-berlin.de
    token:
      from_secret: trigger_token
    fork: true
    repositories:
      - enowars/Enowars4DevOps

trigger:
  branch:
  - main
  event:
  - push
