version: '3'

services:
  poolcide-backend:
    build: .
    ports:
      - 9002:8000
    environment:
     - MONGO_ENABLED=1
     - MONGO_HOST=poolcide-db
     - MONGO_PORT=27017
     - MONGO_USER=enoislove
     - MONGO_PASSWORD=enoislife
  poolcide-db:
    image: mongo
    volumes:
      - ./poolcide_db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: enoislove
      MONGO_INITDB_ROOT_PASSWORD: enoislife
